var WTData = function(title, details, util, api ) {
	this.title = title;
	this.details = details;
	this.util = util;
	this.api = api;
};

WTData.prototype.appendLinkItem = function( list, link, name ) {
	if(!name) name = link;
	var vlink = link.replace(/\s/g, '_');
	list.append($j('<li></li>').append($j('<a href="'+vlink+'"></a>').append(name)));
};

WTData.prototype.populateList = function( list, data ) {
	var me = this;
	me.appendLinkItem( list, data.location, "<b>DOWNLOAD</b>" );

	var types = $j('<ul></ul>');
	$j.each(data.types, function(i, type) {
		types.append($j('<li>'+type+'</li>'));
	});
	list.append($j('<li><b>Data Types</b></li>')).append(types);

	if(data.inputtoworkflows.length) {
		var plinks = $j('<ul></ul>');
		$j.each(data.inputtoworkflows, function(i, link) {
			var name = link.replace(/.+\//, '');
			me.appendLinkItem( plinks, link, name );
		});
		list.append($j('<li><b>Used as Input in the following Workflows:</b></li>')).append(plinks);
	}

	if(data.generatedbyworkflows.length) {
		var plinks = $j('<ul></ul>');
		$j.each(data.generatedbyworkflows, function(i, link) {
			var name = link.replace(/.+\//, '');
			me.appendLinkItem( plinks, link, name );
		});
		list.append($j('<li><b>Generated by the following Workflows:</b></li>')).append(plinks);
	}

	/*var plinks = $j('<ul></ul>');
	$j.each(data.pubbylinks, function(i, link) {
		var name = link.replace(/.+\//, '');
		me.appendLinkItem( plinks, link, name );
	});
	list.append($j('<li><b>Usage</b></li>')).append(plinks);*/
};

WTData.prototype.getList = function( item, data ) {
	var list = $j('<ul></ul>');
	var me = this;

	if(data && data.WTData) {
		me.populateList(list, data.WTData);
	}
	item.data('list', list);
	return list;
};


WTData.prototype.display = function( item ) {
	var me = this;

	item.data('numchecked', 0);
	item.data('checked_data', []);
	item.data('data', me.details);

	var list = me.getList( item, me.details );

	var header = $j('<h2 style="margin-bottom:5px;margin-top:0px;padding-top:0px"></h2>').append('Data');
	var toolbar = $j('<div></div>').append(header);
	//toolbar.append(me.util.getHelpButton('add_wflow')));
	item.append(toolbar);
	item.append(list);
};

